static: "static"

routes:
    - url: "/"
      handler: "About->index"
    - url: "/id0"
      handler: "About->index"
    - url: "/terms"
      handler: "About->rules"
    - url: "/rpc"
      handler: "InternalAPI->route"
    - url: "/iapi/timezone"
      handler: "InternalAPI->timezone"
    - url: "/support"
      handler: "Support->index"
    - url: "/support/tickets"
      handler: "Support->list"
    - url: "/support/reply/{num}"
      handler: "Support->AnswerTicket"
    - url: "/support/view/{num}"
      handler: "Support->view"
    - url: "/support/comment/{num}/rate/{num}"
      handler: "Support->rateAnswer"
    - url: "/al_comments/create/support/{num}"
      handler: "Support->makeComment"
    - url: "/al_comments/create/support/reply/{num}"
      handler: "Support->AnswerTicketReply"
    - url: "/support/comment/{num}/delete"
      handler: "Support->deleteComment"
    - url: "/al_comments/create/{text}/{num}"
      handler: "Comment->makeComment"
    - url: "/support/delete/{num}"
      handler: "Support->delete"
    - url: "/support/agent{num}"
      handler: "Support->agent"
    - url: "/support/agent{num}/edit"
      handler: "Support->editAgent"
    - url: "/support/ticket{num}/close"
      handler: "Support->closeTicket"
    - url: "/language"
      handler: "About->language"
    - url: "/language/{text}.js"
      handler: "About->exportJSLanguage"
    - url: "/donate"
      handler: "About->donate"
    - url: "/kb/{slug}"
      handler: "Support->knowledgeBaseArticle"
    - url: "/about:{?!productName}"
      handler: "About->version"
      placeholders:
          productName: "openvk[2]?|libresoc"
    - url: "/about"
      handler: "About->aboutInstance"
    - url: "/privacy"
      handler: "About->Privacy"
    - url: "/badbrowser.php"
      handler: "About->BB"
    - url: "/login"
      handler: "Auth->login"
    - url: "/reg"
      handler: "Auth->register"
    - url: "/logout"
      handler: "Auth->logout"
    - url: "/restore"
      handler: "Auth->restore"
    - url: "/restore/internal-finish"
      handler: "Auth->finishRestoringPassword"
    - url: "/reg/resend"
      handler: "Auth->resendEmail"
    - url: "/regFinish"
      handler: "Auth->verifyEmail"
    - url: "/setSID/{slug}"
      handler: "Auth->su"
    - url: "/unban.php"
      handler: "Auth->unbanThemself"
    - url: "/revokeAllTokens"
      handler: "Auth->revokeAllTokens"
    - url: "/settings"
      handler: "User->settings"
    - url: "/settings/2fa"
      handler: "User->twoFactorAuthSettings"
    - url: "/settings/2fa/disable"
      handler: "User->disableTwoFactorAuth"
    - url: "/settings/reset_theme"
      handler: "User->resetThemepack"
    - url: "/settings/change_email"
      handler: "User->emailChangeFinish"
    - url: "/settings/deactivate"
      handler: "User->deactivate"
    - url: "/settings/reactivate"
      handler: "Auth->reactivatePage"
    - url: "/coins_transfer"
      handler: "User->coinsTransfer"
    - url: "/increase_social_credits"
      handler: "User->increaseRating"
    - url: "/id{num}"
      handler: "User->view"
    - url: "/friends{num}"
      handler: "User->friends"
    - url: "/edit"
      handler: "User->edit"
    - url: "/edit/verify_phone"
      handler: "User->verifyPhone"
    - url: "/setSub/user"
      handler: "User->sub"
    - url: "/setSub/club"
      handler: "Group->sub"
    - url: "/setSub/v4/club"
      handler: "Group->attend"
    - url: "/groups/{num}/setNewOwner/{num}"
      handler: "Group->changeOwner"
    - url: "/comment{num}/like"
      handler: "Comment->like"
    - url: "/comment{num}/delete"
      handler: "Comment->deleteComment"
    - url: "/notifications"
      handler: "Notification->feed"
    - url: "/feed"
      handler: "Wall->feed"
    - url: "/feed/all"
      handler: "Wall->globalFeed"
    - url: "/feed/hashtag/{?hashTag}"
      handler: "Wall->hashtagFeed"
      placeholders:
          hashTag: ".++"
    - url: "/wall{num}"
      handler: "Wall->wall"
    - url: "/wall{num}/rss"
      handler: "Wall->rss"
    - url: "/wall{num}/makePost"
      handler: "Wall->makePost"
    - url: "/wall/edit"
      handler: "Wall->edit"
    - url: "/wall{num}_{num}"
      handler: "Wall->post"
    - url: "/wall{num}_{num}/like"
      handler: "Wall->like"
    - url: "/wall{num}_{num}/repost"
      handler: "Wall->share"
    - url: "/wall{num}_{num}/delete"
      handler: "Wall->delete"
    - url: "/wall{num}_{num}/pin"
      handler: "Wall->pin"
    - url: "/wall/accept"
      handler: "Wall->accept"
    - url: "/wall/decline"
      handler: "Wall->decline"
    - url: "/blob_{text}/{?path}.{text}"
      handler: "Blob->file"
      placeholders:
          path: "[A-z0-9\\-_\\/]{3,}"
    - url: "/themepack/{text}/{?version}/{?resClass}/{?any}"
      handler: "Themepacks->resource"
      placeholders:
          version: "(?:[0-9]+\\.?)+"
          resClass: "stylesheet|resource"
          any: ".+"
    - url: "/albums{num}"
      handler: "Photos->albumList"
    - url: "/albums/create"
      handler: "Photos->createAlbum"
    - url: "/album{num}_{num}"
      handler: "Photos->album"
    - url: "/album{num}_{num}/edit"
      handler: "Photos->editAlbum"
    - url: "/album{num}_{num}/delete"
      handler: "Photos->deleteAlbum"
    - url: "/album{num}_{num}/remove_photo/{num}"
      handler: "Photos->unlinkPhoto"
    - url: "/photos/upload"
      handler: "Photos->uploadPhoto"
    - url: "/photo{num}_{num}"
      handler: "Photos->photo"
    - url: "/photos/thumbnails/{num}_{text}.jpeg"
      handler: "Photos->thumbnail"
    - url: "/photos/{text}"
      handler: "Photos->absolutePhoto"
    - url: "/photo{num}_{num}/edit"
      handler: "Photos->editPhoto"
    - url: "/photo{num}_{num}/delete"
      handler: "Photos->deletePhoto"
    - url: "/al_avatars"
      handler: "User->setAvatar"
    - url: "/delete_avatar"
      handler: "User->deleteAvatar"
    - url: "/videos{num}"
      handler: "Videos->list"
    - url: "/videos/upload"
      handler: "Videos->upload"
    - url: "/video{num}_{num}"
      handler: "Videos->view"
    - url: "/video{num}_{num}/edit"
      handler: "Videos->edit"
    - url: "/video{num}_{num}/remove"
      handler: "Videos->remove"
    - url: "/video{num}_{num}/like"
      handler: "Videos->like"
    - url: "/player/upload"
      handler: "Audio->upload"
    - url: "/audios{num}"
      handler: "Audio->list"
    - url: "/audios/popular"
      handler: "Audio->popular"
    - url: "/audios/new"
      handler: "Audio->new"
    - url: "/audio{num}_{num}/embed.xhtml"
      handler: "Audio->embed"
    - url: "/audio{num}/listen"
      handler: "Audio->listen"
    - url: "/audios/search"
      handler: "Audio->search"
    - url: "/audios/newPlaylist"
      handler: "Audio->newPlaylist"
    - url: "/audios/context"
      handler: "Audio->apiGetContext"
    - url: "/playlist{num}_{num}"
      handler: "Audio->playlist"
    - url: "/playlist{num}_{num}/edit"
      handler: "Audio->editPlaylist"
    - url: "/playlist{num}/action"
      handler: "Audio->playlistAction"
    - url: "/playlists{num}"
      handler: "Audio->playlists"
    - url: "/audio{num}/action"
      handler: "Audio->action"
    - url: "/{?!club}{num}"
      handler: "Group->view"
      placeholders:
          club: "club|public|event"
    - url: "/club{num}/edit"
      handler: "Group->edit"
    - url: "/club{num}/al_avatar"
      handler: "Group->setAvatar"
    - url: "/club{num}/delete_avatar"
      handler: "Group->deleteAvatar"
    - url: "/club{num}/backdrop"
      handler: "Group->editBackdrop"
    - url: "/club{num}/stats"
      handler: "Group->statistics"
    - url: "/club{num}/followers"
      handler: "Group->followers"
    - url: "/club{num}/followers/{num}"
      handler: "Group->admin"
    - url: "/club{num}/setAdmin"
      handler: "Group->modifyAdmin"
    - url: "/club{num}/suggested"
      handler: "Group->suggested"
    - url: "/groups{num}"
      handler: "User->groups"
    - url: "/groups_pin"
      handler: "User->pinClub"
    - url: "/groups_create"
      handler: "Group->create"
    - url: "/board{num}"
      handler: "Topics->board"
    - url: "/board{num}/create"
      handler: "Topics->create"
    - url: "/topic{num}_{num}"
      handler: "Topics->topic"
    - url: "/topic{num}_{num}/edit"
      handler: "Topics->edit"
    - url: "/topic{num}_{num}/delete"
      handler: "Topics->delete"
    - url: "/im"
      handler: "Messenger->index"
    - url: "/im/sel{num}"
      handler: "Messenger->app"
    - url: "/im{num}"
      handler: "Messenger->events"
    - url: "/nim{num}"
      handler: "Messenger->VKEvents"
    - url: "/im/api/messages{num}/{num}.json"
      handler: "Messenger->apiGetMessages"
    - url: "/im/api/messages{num}/create.json"
      handler: "Messenger->apiWriteMessage"
    - url: "/search"
      handler: "Search->index"
    - url: "/search/content"
      handler: "ContentSearch->index"
    - url: "/notes{num}"
      handler: "Notes->list"
    - url: "/note{num}_{num}"
      handler: "Notes->view"
    - url: "/notes/prerender"
      handler: "Notes->preView"
    - url: "/notes/create"
      handler: "Notes->create"
    - url: "/note{num}_{num}/edit"
      handler: "Notes->edit"
    - url: "/note{num}_{num}/delete"
      handler: "Notes->delete"
    - url: "/invite"
      handler: "About->invite"
    - url: "/away.php"
      handler: "Away->away"
    - url: "/away.php/{num}"
      handler: "Away->view"
    - url: "/gift{num}_{num}.png"
      handler: "Gifts->giftImage"
    - url: "/gifts{num}"
      handler: "Gifts->userGifts"
    - url: "/gifts"
      handler: "Gifts->stub"
    - url: "/app{num}"
      handler: "Apps->play"
    - url: "/apps"
      handler: "Apps->list"
    - url: "/editapp"
      handler: "Apps->edit"
    - url: "/apps/uninstall"
      handler: "Apps->unInstall"
    - url: "/poll{num}"
      handler: "Poll->view"
    - url: "/poll{num}/voters"
      handler: "Poll->voters"
    - url: "/admin"
      handler: "Admin->index"
    - url: "/admin/users"
      handler: "Admin->users"
    - url: "/admin/users/id{num}"
      handler: "Admin->user"
    - url: "/admin/clubs"
      handler: "Admin->clubs"
    - url: "/admin/clubs/id{num}"
      handler: "Admin->club"
    - url: "/admin/vouchers"
      handler: "Admin->vouchers"
    - url: "/admin/vouchers/id{num}"
      handler: "Admin->voucher"
    - url: "/admin/gifts"
      handler: "Admin->giftCategories"
    - url: "/admin/gifts/id{num}"
      handler: "Admin->gift"
    - url: "/admin/gifts/{slug}.{num}.meta"
      handler: "Admin->giftCategory"
    - url: "/admin/gifts/{slug}.{num}/"
      handler: "Admin->gifts"
    - url: "/admin/ban/{num}"
      handler: "Admin->quickBan"
    - url: "/admin/unban/{num}"
      handler: "Admin->quickUnban"
    - url: "/admin/warn/{num}"
      handler: "Admin->quickWarn"
    - url: "/admin/support/ban/{num}"
      handler: "Support->quickBanInSupport"
    - url: "/admin/support/unban/{num}"
      handler: "Support->quickUnbanInSupport"
    - url: "/admin/support/reports"
      handler: "Report->list"
    - url: "/scumfeed"
      handler: "Report->list"
    - url: "/admin/report{num}"
      handler: "Report->view"
    - url: "/admin/report{num}"
      handler: "Report->view"
    - url: "/admin/reportAction{num}"
      handler: "Report->action"
    - url: "/report/{num}"
      handler: "Report->create"
    - url: "/admin/bannedLinks"
      handler: "Admin->bannedLinks"
    - url: "/admin/bannedLink/id{num}"
      handler: "Admin->bannedLink"
    - url: "/admin/bannedLink/id{num}/unban"
      handler: "Admin->unbanLink"
    - url: "/admin/music"
      handler: "Admin->music"
    - url: "/admin/music/{num}/edit"
      handler: "Admin->editMusic"
    - url: "/admin/playlist/{num}/edit"
      handler: "Admin->editPlaylist"
    - url: "/admin/user{num}/bans"
      handler: "Admin->bansHistory"
    - url: "/upload/photo/{text}"
      handler: "VKAPI->photoUpload"
    - url: "/method/{text}.{text}"
      handler: "VKAPI->route"
    - url: "/token"
      handler: "VKAPI->tokenLogin"
    - url: "/authorize"
      handler: "VKAPI->OAuthLogin"
    - url: "/admin/sandbox"
      handler: "About->sandbox"
    - url: "/admin/chandler/groups"
      handler: "Admin->chandlerGroups"
    - url: "/admin/chandler/groups/{slug}"
      handler: "Admin->chandlerGroup"
    - url: "/admin/chandler/users/{slug}"
      handler: "Admin->chandlerUser"
    - url: "/noSpam"
      handler: "NoSpam->index"
    - url: "/al_abuse/search"
      handler: "NoSpam->search"
    - url: "/admin/logs"
      handler: "Admin->logs"
    - url: "/internal/wall{num}"
      handler: "Wall->wallEmbedded"
    - url: "/robots.txt"
      handler: "About->robotsTxt"
    - url: "/humans.txt"
      handler: "About->humansTxt"
    - url: "/dev"
      handler: "About->dev"
    - url: "/iapi/getPhotosFromPost/{num}_{num}"
      handler: "InternalAPI->getPhotosFromPost"
    - url: "/tour"
      handler: "About->tour"
    - url: "/{?shortCode}"
      handler: "UnknownTextRouteStrategy->delegate"
      placeholders:
          shortCode: "[a-z][a-z0-9\\@\\.\\_]{0,30}[a-z0-9]"
    - url: "/maintenance/{text}"
      handler: "Maintenance->section"
    - url: "/maintenances/"
      handler: "Maintenance->all"
