static: "static"

routes:
    - url: "/"
      handler: "About->index"
    - url: "/id0"
      handler: "About->index"
    - url: "/terms"
      handler: "About->rules"
    - url: "/rpc"
      handler: "InternalAPI->route"
    - url: "/support"
      handler: "Support->index"
    - url: "/support/tickets"
      handler: "Support->list"
    - url: "/support/reply/{num}"
      handler: "Support->AnswerTicket"
    - url: "/support/view/{num}"
      handler: "Support->view"
    - url: "/al_comments.pl/create/support/{num}"
      handler: "Support->makeComment"
    - url: "/al_comments.pl/create/support/reply/{num}"
      handler: "Support->AnswerTicketReply"
    - url: "/support/delete/{num}"
      handler: "Support->delete"
    - url: "/language"
      handler: "About->language"
    - url: "/donate"
      handler: "About->donate"
    - url: "/kb/{slug}"
      handler: "Support->knowledgeBaseArticle"
    - url: "/about:{?!productName}"
      handler: "About->version"
      placeholders:
          productName: "openvk[2]?|libresoc"
    - url: "/privacy"
      handler: "About->Privacy"
    - url: "/badbrowser.php"
      handler: "About->BB"
    - url: "/login"
      handler: "Auth->login"
    - url: "/reg"
      handler: "Auth->register"
    - url: "/logout"
      handler: "Auth->logout"
    - url: "/restore.pl"
      handler: "Auth->restore"
    - url: "/restore.pl/internal-finish"
      handler: "Auth->finishRestoringPassword"
    - url: "/setSID/{slug}"
      handler: "Auth->su"
    - url: "/settings"
      handler: "User->settings"
    - url: "/id{num}"
      handler: "User->view"
    - url: "/friends{num}"
      handler: "User->friends"
    - url: "/edit"
      handler: "User->edit"
    - url: "/edit/verify_phone.pl"
      handler: "User->verifyPhone"
    - url: "/setSub/user"
      handler: "User->sub"
    - url: "/setSub/club"
      handler: "Group->sub"
    - url: "/setSub/v4/club"
      handler: "Group->attend"
    - url: "/al_comments.pl/create/{text}/{num}"
      handler: "Comment->makeComment"
    - url: "/comment{num}/like"
      handler: "Comment->like"
    - url: "/comment{num}/delete"
      handler: "Comment->deleteComment"
    - url: "/notifications"
      handler: "Notification->feed"
    - url: "/feed"
      handler: "Wall->feed"
    - url: "/feed/all"
      handler: "Wall->globalFeed"
    - url: "/feed/hashtag/{?hashTag}"
      handler: "Wall->hashtagFeed"
      placeholders:
          hashTag: ".++"
    - url: "/wall{num}"
      handler: "Wall->wall"
    - url: "/wall{num}/makePost"
      handler: "Wall->makePost"
    - url: "/wall{num}_{num}"
      handler: "Wall->post"
    - url: "/wall{num}_{num}/like"
      handler: "Wall->like"
    - url: "/wall{num}_{num}/repost"
      handler: "Wall->share"
    - url: "/wall{num}_{num}/delete"
      handler: "Wall->delete"
    - url: "/blob_{text}/{text}.{text}"
      handler: "Blob->file"
    - url: "/themepack/{text}/{?version}/{?resClass}/{?any}"
      handler: "Themepacks->resource"
      placeholders:
          version: "(?:[0-9]+\\.?)+"
          resClass: "stylesheet|resource"
          any: ".+"
    - url: "/albums{num}"
      handler: "Photos->albumList"
    - url: "/albums/create"
      handler: "Photos->createAlbum"
    - url: "/album{num}_{num}"
      handler: "Photos->album"
    - url: "/album{num}_{num}/edit"
      handler: "Photos->editAlbum"
    - url: "/album{num}_{num}/delete.pl"
      handler: "Photos->deleteAlbum"
    - url: "/album{num}_{num}/remove_photo.pl/{num}"
      handler: "Photos->unlinkPhoto"
    - url: "/photos/upload"
      handler: "Photos->uploadPhoto"
    - url: "/photo{num}_{num}"
      handler: "Photos->photo"
    - url: "/photo{num}_{num}/edit"
      handler: "Photos->editPhoto"
    - url: "/photo{num}_{num}/delete"
      handler: "Photos->deletePhoto"
    - url: "/al_avatars.pl"
      handler: "User->setAvatar"
    - url: "/videos{num}"
      handler: "Videos->list"
    - url: "/videos/upload"
      handler: "Videos->upload"
    - url: "/video{num}_{num}"
      handler: "Videos->view"
    - url: "/video{num}_{num}/edit"
      handler: "Videos->edit"
    - url: "/video{num}_{num}/remove"
      handler: "Videos->remove"
    - url: "/{?!club}{num}"
      handler: "Group->view"
      placeholders:
          club: "club|public|event"
    - url: "/club{num}/edit"
      handler: "Group->edit"
    - url: "/club{num}/stats"
      handler: "Group->statistics"
    - url: "/club{num}/followers"
      handler: "Group->followers"
    - url: "/club{num}/followers/{num}"
      handler: "Group->admin"
    - url: "/club{num}/setAdmin.jsp"
      handler: "Group->modifyAdmin"
    - url: "/groups{num}"
      handler: "User->groups"
    - url: "/groups_create"
      handler: "Group->create"
    - url: "/audios{num}"
      handler: "Audios->app"
    - url: "/audios{num}.json"
      handler: "Audios->apiListSongs"
    - url: "/audios/popular.json"
      handler: "Audios->apiListPopSongs"
    - url: "/audios/playlist{num}.json"
      handler: "Audios->apiListPlaylists"
    - url: "/audios/search.json"
      handler: "Audios->apiSearch"
    - url: "/audios/add.json"
      handler: "Audios->apiAdd"
    - url: "/audios/playlist.json"
      handler: "Audios->apiAddPlaylist"
    - url: "/audios/upload.json"
      handler: "Audios->apiUpload"
    - url: "/audios/beacon"
      handler: "Audios->apiBeacon"
    - url: "/im"
      handler: "Messenger->index"
    - url: "/im/sel{num}"
      handler: "Messenger->app"
    - url: "/im{num}"
      handler: "Messenger->events"
    - url: "/nim{num}"
      handler: "Messenger->VKEvents"
    - url: "/im/api/messages{num}/{num}.json"
      handler: "Messenger->apiGetMessages"
    - url: "/im/api/messages{num}/create.json"
      handler: "Messenger->apiWriteMessage"
    - url: "/search"
      handler: "Search->index"
    - url: "/search/content"
      handler: "ContentSearch->index"
    - url: "/notes{num}"
      handler: "Notes->list"
    - url: "/note{num}_{num}"
      handler: "Notes->view"
    - url: "/notes/create"
      handler: "Notes->create"
    - url: "/note{num}_{num}/delete"
      handler: "Notes->delete"
    - url: "/invite"
      handler: "About->invite"
    - url: "/away.php"
      handler: "Away->away"
    - url: "/admin"
      handler: "Admin->index"
    - url: "/admin/users"
      handler: "Admin->users"
    - url: "/admin/users/id{num}"
      handler: "Admin->user"
    - url: "/admin/clubs"
      handler: "Admin->clubs"
    - url: "/admin/clubs/id{num}"
      handler: "Admin->club"
    - url: "/admin/ban.pl/{num}"
      handler: "Admin->quickBan"
    - url: "/admin/warn.pl/{num}"
      handler: "Admin->quickWarn"
    - url: "/method/{text}.{text}"
      handler: "VKAPI->route"
    - url: "/token"
      handler: "VKAPI->tokenLogin"
    - url: "/sandbox_cocksex"
      handler: "About->sandbox"
    - url: "/{?shortCode}"
      handler: "UnknownTextRouteStrategy->delegate"
      placeholders:
          shortCode: "[a-z][a-z0-9\\@\\.\\_]{0,30}[a-z0-9]"
